name: "Setup Git for OSBotify"
description: "Setup Git for OSBotify"

inputs:
  GPG_PASSPHRASE:
    description: "Passphrase used to decrypt GPG key"
    required: true

runs:
  using: composite
  steps:
    - name: Decrypt OSBotify GPG key
      run: cd .github/workflows && gpg --quiet --batch --yes --decrypt --passphrase=${{ inputs.GPG_PASSPHRASE }} --output OSBotify-private-key.asc OSBotify-private-key.asc.gpg
      shell: bash

    - name: Import OSBotify GPG Key
      shell: bash
      run: cd .github/workflows && gpg --import OSBotify-private-key.asc

    - name: Set up git for OSBotify
      shell: bash
      run: |
        git config user.signingkey 367811D53E34168C
        git config commit.gpgsign true
        git config user.name OSBotify
        git config user.email infra+osbotify@expensify.com

    - name: Enable debug logs for git
      shell: bash
      if: runner.debug == '1'
      run: echo "GIT_TRACE=true" >> "$GITHUB_ENV"

    # steps below copied and modified from https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow#authenticating-with-a-github-app
    - name: Generate a token
      id: generate_token
      uses: tibdex/github-app-token@c2055a00597a80f713b78b1650e8d3418f4d9a65
      with:
        app_id: ${{ secrets.OS_BOTIFY_APP_ID }}
        private_key: ${{ secrets.OS_BOTIFY_PRIVATE_KEY }}
        installation_id: ${{ secrets.OS_BOTIFY_INSTALLATION_ID }}

    - name: Use the token
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api octocat
